<?php
declare(strict_types=1);
namespace hexydec\ipaddresses;

class regionMapping {

	/**
	 * Returns a mapping of cloud provider region identifiers to ISO 3166-1 alpha-2 country codes
	 *
	 * @return array An associative array mapping region strings to two-letter country codes
	 */
	public static function get() : array {
		return [

			// AWS / Oracle style regions
			'us-east' => 'us',
			'us-west' => 'us',
			'us-gov-east' => 'us',
			'us-gov-west' => 'us',
			'us-ashburn' => 'us',
			'us-phoenix' => 'us',
			'us-sanjose' => 'us',
			'us-chicago' => 'us',
			'us-saltlake' => 'us',
			'ca-central' => 'ca',
			'ca-west' => 'ca',
			'ca-montreal' => 'ca',
			'ca-toronto' => 'ca',
			'sa-east' => 'br',
			'sa-saopaulo' => 'br',
			'sa-vinhedo' => 'br',
			'sa-bogota' => 'co',
			'sa-santiago' => 'cl',
			'sa-valparaiso' => 'cl',
			'sa-west' => 'cl',
			'mx-central' => 'mx',
			'mx-queretaro' => 'mx',
			'mx-monterrey' => 'mx',
			'eu-west-1' => 'ie',
			'eu-west-2' => 'gb',
			'eu-west-3' => 'fr',
			'eu-central-1' => 'de',
			'eu-central-2' => 'ch',
			'eu-south-1' => 'it',
			'eu-south-2' => 'es',
			'eu-north' => 'se',
			'eu-frankfurt' => 'de',
			'eu-amsterdam' => 'nl',
			'eu-zurich' => 'ch',
			'eu-stockholm' => 'se',
			'eu-milan' => 'it',
			'eu-marseille' => 'fr',
			'eu-madrid' => 'es',
			'eu-paris' => 'fr',
			'eu-london' => 'gb',
			'eu-dcc-dublin' => 'ie',
			'eu-dcc-milan' => 'it',
			'eu-dcc-rating' => 'de',
			'eu-jovanovac' => 'rs',
			'eusc-de-east' => 'de',
			'uk-london' => 'gb',
			'uk-cardiff' => 'gb',
			'uk-gov-london' => 'gb',
			'uk-gov-cardiff' => 'gb',
			'ap-east-1' => 'hk',
			'ap-east-2' => 'my',
			'ap-south-1' => 'in',
			'ap-south-2' => 'in',
			'ap-southeast-1' => 'sg',
			'ap-southeast-2' => 'au',
			'ap-southeast-3' => 'id',
			'ap-southeast-4' => 'au',
			'ap-southeast-5' => 'my',
			'ap-southeast-6' => 'th',
			'ap-southeast-7' => 'th',
			'ap-northeast-1' => 'jp',
			'ap-northeast-2' => 'kr',
			'ap-northeast-3' => 'jp',
			'ap-tokyo' => 'jp',
			'ap-osaka' => 'jp',
			'ap-seoul' => 'kr',
			'ap-singapore' => 'sg',
			'ap-sydney' => 'au',
			'ap-melbourne' => 'au',
			'ap-mumbai' => 'in',
			'ap-hyderabad' => 'in',
			'ap-chuncheon' => 'kr',
			'ap-dcc-gazipur' => 'in',
			'af-south' => 'za',
			'af-johannesburg' => 'za',
			'me-south' => 'bh',
			'me-central-1' => 'ae',
			'me-central-2' => 'sa',
			'me-abudhabi' => 'ae',
			'me-dubai' => 'ae',
			'me-jeddah' => 'sa',
			'me-riyadh' => 'sa',
			'me-dcc-muscat' => 'om',
			'il-central' => 'il',
			'il-jerusalem' => 'il',
			'cn-north' => 'cn',
			'cn-northwest' => 'cn',

			// GCP style regions
			'us-central' => 'us',
			'us-south' => 'us',
			'northamerica-northeast' => 'ca',
			'northamerica-south' => 'mx',
			'southamerica-east' => 'br',
			'southamerica-west' => 'cl',
			'europe-west1' => 'be',
			'europe-west2' => 'gb',
			'europe-west3' => 'de',
			'europe-west4' => 'nl',
			'europe-west6' => 'ch',
			'europe-west8' => 'it',
			'europe-west9' => 'fr',
			'europe-west10' => 'de',
			'europe-west12' => 'it',
			'europe-west15' => 'at',
			'europe-north' => 'fi',
			'europe-central' => 'pl',
			'europe-southwest' => 'es',
			'asia-east1' => 'tw',
			'asia-east2' => 'hk',
			'asia-northeast1' => 'jp',
			'asia-northeast2' => 'jp',
			'asia-northeast3' => 'kr',
			'asia-south1' => 'in',
			'asia-south2' => 'in',
			'asia-southeast1' => 'sg',
			'asia-southeast2' => 'id',
			'asia-southeast3' => 'th',
			'australia-southeast' => 'au',
			'me-west' => 'il',
			'me-central1' => 'qa',
			'me-central2' => 'sa',
			'africa-south' => 'za',

			// Azure style regions
			'eastus' => 'us',
			'eastus2' => 'us',
			'eastus3' => 'us',
			'westus' => 'us',
			'westus2' => 'us',
			'westus3' => 'us',
			'centralus' => 'us',
			'northcentralus' => 'us',
			'southcentralus' => 'us',
			'westcentralus' => 'us',
			'canadacentral' => 'ca',
			'canadaeast' => 'ca',
			'brazilsouth' => 'br',
			'brazilsoutheast' => 'br',
			'brazilus' => 'br',
			'mexicocentral' => 'mx',
			'westeurope' => 'nl',
			'northeurope' => 'ie',
			'uksouth' => 'gb',
			'ukwest' => 'gb',
			'francecentral' => 'fr',
			'francesouth' => 'fr',
			'germanywestcentral' => 'de',
			'germanynorth' => 'de',
			'switzerlandnorth' => 'ch',
			'switzerlandwest' => 'ch',
			'norwayeast' => 'no',
			'norwaywest' => 'no',
			'swedencentral' => 'se',
			'swedensouth' => 'se',
			'polandcentral' => 'pl',
			'italynorth' => 'it',
			'spaincentral' => 'es',
			'austriaeast' => 'at',
			'belgiumcentral' => 'be',
			'denmarkeast' => 'dk',
			'finlandcentral' => 'fi',
			'greececentral' => 'gr',
			'eastasia' => 'hk',
			'southeastasia' => 'sg',
			'japaneast' => 'jp',
			'japanwest' => 'jp',
			'koreacentral' => 'kr',
			'koreasouth' => 'kr',
			'centralindia' => 'in',
			'southindia' => 'in',
			'westindia' => 'in',
			'jioindiawest' => 'in',
			'jioindiacentral' => 'in',
			'australiaeast' => 'au',
			'australiasoutheast' => 'au',
			'australiacentral' => 'au',
			'australiacentral2' => 'au',
			'chinaeast' => 'cn',
			'chinaeast2' => 'cn',
			'chinanorth' => 'cn',
			'chinanorth2' => 'cn',
			'chinanorth3' => 'cn',
			'uaenorth' => 'ae',
			'uaecentral' => 'ae',
			'southafricanorth' => 'za',
			'southafricawest' => 'za',
			'qatarcentral' => 'qa',
			'israelcentral' => 'il',
			'taiwannorth' => 'tw',
			'taiwannorthwest' => 'tw',
			'newzealandnorth' => 'nz',
			'indonesiacentral' => 'id',
			'malaysiawest' => 'my',
			'usgovvirginia' => 'us',
			'usgovarizona' => 'us',
			'usgovtexas' => 'us',
			'usgoviowa' => 'us',
			'usdodeast' => 'us',
			'usdodcentral' => 'us',
		];
	}
}